package GUI;

import Calendar.EnumMatriz;
import Calendar.Matriz;
import java.awt.BorderLayout;
import java.awt.Dimension;

/**
 *
 * @author bryan
 */
public class VistaMatriz extends javax.swing.JDialog {
    private MainFrame frame;
    private Matriz tab;
    /**
     * Creates new form FrameMatrizLunar
     */
    public VistaMatriz(MainFrame frame) {
        this.frame = frame;
        this.tab = new Matriz(frame, 20, 13, 260, EnumMatriz.HAAB);
        this.setLayout(new BorderLayout());
        this.setSize(new Dimension(800, 600));
        this.setTitle("Fase Lunar");    //nombre de la matriz  este frame debe mostrar cualquier matriz tiene que traerel nom
        //this.add(tab,BorderLayout.CENTER);
        //this.tab.inicializar();
        //this.tab.setSize(200,200);
        //this.tab.ordenar();
        //initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
